repos:
    - repo: local
      hooks:
          - id: isort
            name: isort
            stages: [commit]
            language: system
            entry: pipenv run isort --check-only --skip .venv src
            types: [python]

          - id: black
            name: black
            stages: [commit]
            language: system
            entry: pipenv run black --check --exclude="migrations|.venv" src
            types: [python]

          - id: flake8
            name: flake8
            stages: [commit]
            language: system
            entry: pipenv run flake8 src
            types: [python]
            exclude: setup.py

          - id: mypy
            name: mypy
            stages: [commit]
            language: system
            entry: pipenv run mypy src
            types: [python]
            pass_filenames: false

          - id: pytest
            name: pytest
            stages: [commit]
            language: system
            entry: pipenv run pytest tests
            types: [python]
            pass_filenames: false

          - id: pytest-cov
            name: pytest
            stages: [push]
            language: system
            entry: pipenv run pytest tests -p no:warnings --cov=. --cov-fail-under=100
            types: [python]
            pass_filenames: false
