version: "3.9"
services:
    app:
        container_name: flask_app
        build:
            context: .
            dockerfile: Dockerfile
        tty: true
        volumes:
            - ./src:/src
            - ./tests:/tests
        environment:
            - APPLICATION_DB=application
            - POSTGRES_USER=postgres
            - POSTGRES_HOSTNAME=db
            - POSTGRES_PASSWORD=supersecretpassword
            - POSTGRES_PORT=5432
        ports:
            - "5001:80"
        networks:
            - flask-app-network
        depends_on:
            - db

    db:
        container_name: flask_postgres_db
        image: postgres
        tty: true
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=supersecretpassword
        ports:
            - "5433:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - flask-app-network

volumes:
    pgdata:

networks:
    flask-app-network:
        driver: bridge
